-- ============================================================
-- Orders (header) — one row per order
-- ============================================================
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  client_order_id text not null unique,
  created_at timestamptz not null default now(),
  status text not null default 'new'
    check (status in ('new', 'accepted', 'preparing', 'ready', 'completed', 'cancelled')),
  source text not null default 'telegram_web_app',
  telegram_user_id text,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  customer_name text,
  phone text,
  fulfillment_method text not null
    check (fulfillment_method in ('pickup', 'dine_in', 'delivery')),
  address text,
  note text,
  currency text not null default 'USD'
    check (currency in ('USD', 'KHR')),
  subtotal_usd numeric(10, 2) not null check (subtotal_usd >= 0),
  subtotal_khr integer not null check (subtotal_khr >= 0),
  item_count integer not null check (item_count > 0 and item_count <= 99),
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  telegram_user jsonb,
  raw_client jsonb not null default '{}'::jsonb
);

-- ============================================================
-- Order Items (line items) — one row per product per order
-- matches orders_rows.csv structure
-- ============================================================
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  client_order_id text not null,
  created_at timestamptz not null default now(),
  status text not null default 'new',
  customer_name text,
  telegram_user_id text,
  phone text,
  fulfillment_method text,
  currency text,
  subtotal_usd numeric(10, 2),
  subtotal_khr integer,
  quantity integer not null check (quantity > 0),
  name text not null,
  unit_price_usd numeric(10, 2) not null,
  unit_price_khr integer not null
);

-- ============================================================
-- Indexes
-- ============================================================
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status, created_at desc);
create index if not exists orders_telegram_user_id_idx on public.orders (telegram_user_id, created_at desc);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists order_items_client_order_id_idx on public.order_items (client_order_id);

-- ============================================================
-- Row Level Security
-- ============================================================
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Revoke all default permissions
revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_items from anon, authenticated;

-- Grant INSERT (place orders)
grant insert on table public.orders to anon, authenticated;
grant insert on table public.order_items to anon, authenticated;

-- Grant SELECT (view orders — filtered by telegram_user_id on client side)
grant select on table public.orders to anon, authenticated;
grant select on table public.order_items to anon, authenticated;

-- Sequences
grant usage, select on sequence public.orders_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.order_items_id_seq to anon, authenticated, service_role;

-- Service role full access
grant select, insert, update, delete on table public.orders to service_role;
grant select, insert, update, delete on table public.order_items to service_role;

-- ============================================================
-- RLS Policies
-- ============================================================

-- Insert: guests can place orders (strict validation)
drop policy if exists "Guests can place orders" on public.orders;
create policy "Guests can place orders"
on public.orders
for insert
to anon, authenticated
with check (
  status = 'new'
  and source = 'telegram_web_app'
  and item_count > 0
  and item_count <= 99
  and jsonb_typeof(items) = 'array'
  and jsonb_array_length(items) > 0
  and subtotal_usd >= 0
  and subtotal_khr >= 0
);

-- Select: anyone can read (filtering by telegram_user_id enforced in app code)
drop policy if exists "Anyone can view orders" on public.orders;
create policy "Anyone can view orders"
on public.orders
for select
to anon, authenticated
using (true);

-- Insert: guests can insert order items
drop policy if exists "Guests can insert order items" on public.order_items;
create policy "Guests can insert order items"
on public.order_items
for insert
to anon, authenticated
with check (true);

-- Select: anyone can read order items (filtering enforced in app code)
drop policy if exists "Anyone can view order items" on public.order_items;
create policy "Anyone can view order items"
on public.order_items
for select
to anon, authenticated
using (true);
